In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn import neighbors , datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
iris_X.shape

(150, 4)

In [2]:
iris_y.shape

(150,)

In [3]:
iris_X[1,:]

array([4.9, 3. , 1.4, 0.2])

In [7]:
np.unique(iris_y)

array([0, 1, 2])

In [8]:
from sklearn.model_selection import train_test_split
X_train ,X_test , y_train,y_test = train_test_split(iris_X,iris_y,test_size=50,random_state=0)
X_train.shape

(100, 4)

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
X_train[1,:]
X_test[1,:]

array([0.55172414, 0.09090909, 0.56603774, 0.375     ])

In [25]:
clf = neighbors.KNeighborsClassifier(n_neighbors=15,p = 2)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
cm

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  1, 15]], dtype=int64)

In [27]:
from sklearn.metrics import  classification_report
clfRe = classification_report(y_pred,y_test)
print(clfRe)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.95      1.00      0.97        18
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

